"""Added emailVerifiedAt column

Revision ID: f3fbce694729
Revises: 183c7953853c
Create Date: 2026-03-14 12:47:12.095209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3fbce694729'
down_revision: Union[str, Sequence[str], None] = '183c7953853c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emailVerifiedAt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'emailVerifiedAt')
    # ### end Alembic commands ###
